### PR TITLE
Add intro paragraph

### LINKED ISSUE #7: Add paragraph to top of sidebar explaining what Code for IATI is
Add this text to the top:

> Tools and guidance contributed by community members, in support of IATI infrastructure, publishers and data users.

### PR DESCRIPTION
**Pull request by markbrough**
Fixes #7 - looks like the below. I took the intro paragraph from the one we currently use on [codeforiati.org](https://codeforiati.org)

image

### CODE REVIEW

**Review by notshi — COMMENTED** [review]
This new addition will change the file to not be purely markdown (apart from the linebreaks) - is this okay and if not, is there a way to add the intro paragraph without adding html?

Otherwise, this looks good to me.

**Comment by markbrough** [comment]
@notshi Yeah - unfortunately you can't add classes to paragraphs in pure markdown. Given that there don't appear to be any other `<p>` elements in the sidebar, we could just remove the class and make it pure markdown? I didn't do this because I thought it might be confusing if `<p>` elements ever did get added in the future, but what do you think?

**Comment by notshi** [comment]
@markbrough We could use a header element `<h4>` or `####` instead and include the css. This would keep it purely markdown.

So for example, the new paragraph would be:

```markdown
#### Tools and guidance contributed by community members, in support of IATI infrastructure, publishers and data users.
```
And the css would be:

```css
h4 {
	margin-top: 0.5rem;
	margin-bottom: 1rem;
	margin-left: 32px;
	margin-right: 10px;
	font-size: 1.25rem;
	font-weight: 300;
	display: block;
}
```

**Comment by markbrough** [comment]
Thanks @notshi I think this works well! Have pushed a new commit - see what you think!

**Review by notshi — CHANGES_REQUESTED** [review]
This looks great!

One thing - could we move the new `h4` css to line 77 so it's beneath `h3`?

**Comment by markbrough** [comment]
Good point, @notshi! Done!

**Review by notshi — APPROVED** [review]
Fantastic!

**Comment by andylolz** [comment]
Thanks both, this is great!

**Pull request merged**
